### ISSUE TITLE
Please delete/hide this repo

### ISSUE THREAD

**Issue by Yorko** [xeniasuper/ML-coursera-yandex-mipt#1]
It violates Coursera Honor Code.

**Comment by xeniasuper** [comment]
well, i've made the repository private. however, i think that it's
students' problem if they copy others' code. they came to coursera to get
skills and they paid money. so that's their decision not to get skills.
everybody knows that nobody cares about coursera certificates, but skills
is the thing that's valuable.

ср, 7 нояб. 2018 г. в 1:29, Yury Kashnitskiy <notifications@github.com>:
